# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gaoming/git/iio/libiio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gaoming/git/iio/libiio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gaoming/git/iio/libiio/CMakeFiles /home/gaoming/git/iio/libiio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gaoming/git/iio/libiio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iio

# Build rule for target.
iio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iio
.PHONY : iio

# fast build rule for target.
iio/fast:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/build
.PHONY : iio/fast

#=============================================================================
# Target rules for targets named iiod

# Build rule for target.
iiod: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iiod
.PHONY : iiod

# fast build rule for target.
iiod/fast:
	$(MAKE) -f iiod/CMakeFiles/iiod.dir/build.make iiod/CMakeFiles/iiod.dir/build
.PHONY : iiod/fast

#=============================================================================
# Target rules for targets named iio_adi_xflow_check

# Build rule for target.
iio_adi_xflow_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iio_adi_xflow_check
.PHONY : iio_adi_xflow_check

# fast build rule for target.
iio_adi_xflow_check/fast:
	$(MAKE) -f tests/CMakeFiles/iio_adi_xflow_check.dir/build.make tests/CMakeFiles/iio_adi_xflow_check.dir/build
.PHONY : iio_adi_xflow_check/fast

#=============================================================================
# Target rules for targets named iio_genxml

# Build rule for target.
iio_genxml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iio_genxml
.PHONY : iio_genxml

# fast build rule for target.
iio_genxml/fast:
	$(MAKE) -f tests/CMakeFiles/iio_genxml.dir/build.make tests/CMakeFiles/iio_genxml.dir/build
.PHONY : iio_genxml/fast

#=============================================================================
# Target rules for targets named iio_info

# Build rule for target.
iio_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iio_info
.PHONY : iio_info

# fast build rule for target.
iio_info/fast:
	$(MAKE) -f tests/CMakeFiles/iio_info.dir/build.make tests/CMakeFiles/iio_info.dir/build
.PHONY : iio_info/fast

#=============================================================================
# Target rules for targets named iio_readdev

# Build rule for target.
iio_readdev: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iio_readdev
.PHONY : iio_readdev

# fast build rule for target.
iio_readdev/fast:
	$(MAKE) -f tests/CMakeFiles/iio_readdev.dir/build.make tests/CMakeFiles/iio_readdev.dir/build
.PHONY : iio_readdev/fast

#=============================================================================
# Target rules for targets named iio_reg

# Build rule for target.
iio_reg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iio_reg
.PHONY : iio_reg

# fast build rule for target.
iio_reg/fast:
	$(MAKE) -f tests/CMakeFiles/iio_reg.dir/build.make tests/CMakeFiles/iio_reg.dir/build
.PHONY : iio_reg/fast

buffer.o: buffer.c.o
.PHONY : buffer.o

# target to build an object file
buffer.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/buffer.c.o
.PHONY : buffer.c.o

buffer.i: buffer.c.i
.PHONY : buffer.i

# target to preprocess a source file
buffer.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/buffer.c.i
.PHONY : buffer.c.i

buffer.s: buffer.c.s
.PHONY : buffer.s

# target to generate assembly for a file
buffer.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/buffer.c.s
.PHONY : buffer.c.s

channel.o: channel.c.o
.PHONY : channel.o

# target to build an object file
channel.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/channel.c.o
.PHONY : channel.c.o

channel.i: channel.c.i
.PHONY : channel.i

# target to preprocess a source file
channel.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/channel.c.i
.PHONY : channel.c.i

channel.s: channel.c.s
.PHONY : channel.s

# target to generate assembly for a file
channel.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/channel.c.s
.PHONY : channel.c.s

context.o: context.c.o
.PHONY : context.o

# target to build an object file
context.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/context.c.o
.PHONY : context.c.o

context.i: context.c.i
.PHONY : context.i

# target to preprocess a source file
context.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/context.c.i
.PHONY : context.c.i

context.s: context.c.s
.PHONY : context.s

# target to generate assembly for a file
context.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/context.c.s
.PHONY : context.c.s

device.o: device.c.o
.PHONY : device.o

# target to build an object file
device.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/device.c.o
.PHONY : device.c.o

device.i: device.c.i
.PHONY : device.i

# target to preprocess a source file
device.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/device.c.i
.PHONY : device.c.i

device.s: device.c.s
.PHONY : device.s

# target to generate assembly for a file
device.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/device.c.s
.PHONY : device.c.s

iiod-client.o: iiod-client.c.o
.PHONY : iiod-client.o

# target to build an object file
iiod-client.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/iiod-client.c.o
.PHONY : iiod-client.c.o

iiod-client.i: iiod-client.c.i
.PHONY : iiod-client.i

# target to preprocess a source file
iiod-client.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/iiod-client.c.i
.PHONY : iiod-client.c.i

iiod-client.s: iiod-client.c.s
.PHONY : iiod-client.s

# target to generate assembly for a file
iiod-client.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/iiod-client.c.s
.PHONY : iiod-client.c.s

local.o: local.c.o
.PHONY : local.o

# target to build an object file
local.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/local.c.o
.PHONY : local.c.o

local.i: local.c.i
.PHONY : local.i

# target to preprocess a source file
local.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/local.c.i
.PHONY : local.c.i

local.s: local.c.s
.PHONY : local.s

# target to generate assembly for a file
local.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/local.c.s
.PHONY : local.c.s

lock.o: lock.c.o
.PHONY : lock.o

# target to build an object file
lock.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/lock.c.o
.PHONY : lock.c.o

lock.i: lock.c.i
.PHONY : lock.i

# target to preprocess a source file
lock.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/lock.c.i
.PHONY : lock.c.i

lock.s: lock.c.s
.PHONY : lock.s

# target to generate assembly for a file
lock.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/lock.c.s
.PHONY : lock.c.s

network.o: network.c.o
.PHONY : network.o

# target to build an object file
network.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/network.c.o
.PHONY : network.c.o

network.i: network.c.i
.PHONY : network.i

# target to preprocess a source file
network.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/network.c.i
.PHONY : network.c.i

network.s: network.c.s
.PHONY : network.s

# target to generate assembly for a file
network.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/network.c.s
.PHONY : network.c.s

utilities.o: utilities.c.o
.PHONY : utilities.o

# target to build an object file
utilities.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/utilities.c.o
.PHONY : utilities.c.o

utilities.i: utilities.c.i
.PHONY : utilities.i

# target to preprocess a source file
utilities.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/utilities.c.i
.PHONY : utilities.c.i

utilities.s: utilities.c.s
.PHONY : utilities.s

# target to generate assembly for a file
utilities.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/utilities.c.s
.PHONY : utilities.c.s

xml.o: xml.c.o
.PHONY : xml.o

# target to build an object file
xml.c.o:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/xml.c.o
.PHONY : xml.c.o

xml.i: xml.c.i
.PHONY : xml.i

# target to preprocess a source file
xml.c.i:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/xml.c.i
.PHONY : xml.c.i

xml.s: xml.c.s
.PHONY : xml.s

# target to generate assembly for a file
xml.c.s:
	$(MAKE) -f CMakeFiles/iio.dir/build.make CMakeFiles/iio.dir/xml.c.s
.PHONY : xml.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... iio"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... iiod"
	@echo "... iio_adi_xflow_check"
	@echo "... iio_genxml"
	@echo "... iio_info"
	@echo "... iio_readdev"
	@echo "... iio_reg"
	@echo "... buffer.o"
	@echo "... buffer.i"
	@echo "... buffer.s"
	@echo "... channel.o"
	@echo "... channel.i"
	@echo "... channel.s"
	@echo "... context.o"
	@echo "... context.i"
	@echo "... context.s"
	@echo "... device.o"
	@echo "... device.i"
	@echo "... device.s"
	@echo "... iiod-client.o"
	@echo "... iiod-client.i"
	@echo "... iiod-client.s"
	@echo "... local.o"
	@echo "... local.i"
	@echo "... local.s"
	@echo "... lock.o"
	@echo "... lock.i"
	@echo "... lock.s"
	@echo "... network.o"
	@echo "... network.i"
	@echo "... network.s"
	@echo "... utilities.o"
	@echo "... utilities.i"
	@echo "... utilities.s"
	@echo "... xml.o"
	@echo "... xml.i"
	@echo "... xml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

